title: Hello World
author: Florian Beau
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An exercise at using GitHub Pages
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
